create table Customer_Master(CIFNO int(10) primary key,
fname varchar(20) not null,
lname varchar(20) not null,
nationality varchar(20) not null,
address varchar(20) not null,
religion varchar(20) not null, 
nod varchar(20) not null,
file1 varchar(120) not null,
file2 varchar(120) not null,
caste varchar(20) not null,
cbof varchar(20) not null,
c varchar(20) not null,
p varchar(20) not null,
e1 varchar(20) not null,
ca varchar(20) not null,
aa varchar(20) not null )